name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Check documentation prose
        run: pixi run vale-check

      - name: Deploy docs
        run: pixi exec --with mkdocs-material --with pymdown-extensions mkdocs gh-deploy --force --strict
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
